Add skip option for skipping existing files (#64)
SDFIdk/CDSETool pull request #65
Opened 2024-01-08 13:46 UTC by kalxas

Implements #64

2024-01-08 20:18 UTC, pjonsson commented
You should get an official opinion from someone who represents the project, but I feel the skip behavior should be the default (who wants to download a file they already have unless it's broken?), and the flag should be about forcing a download when a file already exists.

2024-01-08 21:10 UTC, kalxas commented
Thank you @pjonsson for the feedback, I agree about the default behavior but I did not want to propose a change of it on my first pull request :)

2024-01-15 08:31 UTC, subnet001 commented
@kalxas Thanks for the contribuiton! I agree with you and @pjonsson about the default behavior, it seems like the right way of doing things. If you're up for it, please feel free to update your merge request to implement it, otherwise i can merge this as is for now, once it passes the pylint / black checks.

2024-01-15 14:00 UTC, pedep requested changes
Just a few changes to make the option a bit more accessible, otherwise LGTM :+1: 

I would also like to see the `os.path.join(path, filename.replace(".SAFE", ".zip"))` statement `DRY`ed, since its used twice now.

 something like
 
 ```python
 result_path = os.path.join(path, filename.replace(".SAFE", ".zip"))
 # [...]
 if skip and os.path.exists(result_path)
 # [...]
 shutil.move(tmp, result_path)
 ```

2024-01-15 14:29 UTC, kalxas commented
Thank you, I will make the fixes in this PR and let you know to review

2024-01-15 15:08 UTC, kalxas commented on src/cdsetool/cli.py
> +            features, path, {"monitor": StatusMonitor(), "concurrency": concurrency, "skip": skip}
Fixed

2024-01-15 15:08 UTC, kalxas commented on src/cdsetool/download.py
> +        return feature.get("id")
Fixed

2024-01-15 15:19 UTC, kalxas commented
@subnet001 default is now to skip existing files.

2024-01-15 15:26 UTC, kalxas commented
@subnet001 @pedep can you please enable the checks?

2024-01-15 17:24 UTC, kalxas commented
Once this passes CI, I would be happy to squash the PR with a better commit message

2024-01-15 17:35 UTC, pedep approved these changes
Looks good to me :+1:

Thank you for your contribution :tada:

2024-01-15 17:36 UTC, merged